### ISSUE TITLE
Fehler bei Aufruf der Rechnung unter "Mein Konto"

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/157-modul-pdf-anhang-artikeldetailseite#1]
Während das Modul PDF Rechnung grundsätzlich funktioniert, führt es beim Aufruf als Kunde unter Mein Konto zu einem Fehler.
zc 157f
php 8.0.28

Die Browsermeldung (Chromium) lautet:

```
This site can’t be reached
The webpage at https://www.beispiel.de/index.php?main_page=rl_invoice3&fn=838_dfc4f653a19d6aec55c224d08c5c6ba8.pdf&order=838 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

In den Logs ist folgender Eintrag zu finden:

```
[13-Jun-2023 10:25:07 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to undefined function symlink() in /includes/modules/pages/rl_invoice3/header_php.php:103
Stack trace:
#0 /index.php(36): require()
#1 {main}
thrown in /includes/modules/pages/rl_invoice3/header_php.php on line 103

[13-Jun-2023 10:25:07 Europe/Berlin] Request URI: /index.php?main_page=rl_invoice3&fn=838_dfc4f653a19d6aec55c224d08c5c6ba8.pdf&order=838, IP address: 2a02:8108:94c0:27a0:abab:2630:2428:782e
--> PHP Fatal error: Uncaught Error: Call to undefined function symlink() in /includes/modules/pages/rl_invoice3/header_php.php:103
Stack trace:
#0 /index.php(36): require()
#1 {main}
thrown in /includes/modules/pages/rl_invoice3/header_php.php on line 103.
```

**Comment by webconcept-one** [comment]
Ich meine PDF Rechnung. Gehört wohl zum Gundsystem.
